# AWSTemplateFormatVersion: 2010-09-09
# Description: ---
# Metadata: 

# Parameters: 

# Mappings: 

# Conditions: 
Transform: AWS::Serverless-2016-10-31
Resources:
  S1:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: 'a3-s1-test'
  S1Policy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref S1
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 's3:PutObject'
            Effect: Allow




  a3Artifacts:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: a3-artifacts
    DeletionPolicy: Retain
  BodyReader:
    Type: 'AWS::Serverless::Function'
    DeletionPolicy: Retain
    Properties:
      Architectures: ['x86_64']
      Runtime: python3.8
      CodeUri: body-reader/body-reader.zip
      Handler: lambda_function.lambda_handler
      FunctionName: a3-body-reader
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket:
              Ref: S1
            Events: s3:ObjectCreated:*
      Role: arn:aws:iam::828815413195:role/a3-body-reader-role
  BodyReaderRole:
    Type: 'AWS::IAM::Role'
    DeletionPolicy: Retain
    Properties:
      RoleName: a3-body-reader-role
      AssumeRolePolicyDocument: 
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: [lambda.amazonaws.com]
          Action: [sts:AssumeRole]
      Policies:
      - PolicyName: GetS3Objects
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Sid: VisualEditor0
            Effect: Allow
            Action:
            - s3:GetObject
            - s3:GetObjectAttributes
            - s3:PutObject
            Resource: arn:aws:s3:::*
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole